### ISSUE TITLE
Allow RAs to override classes offered from server (JBoss)

### ISSUE THREAD

**Issue by SummaNetworks** [RestComm/jain-slee#100]
Same as for the services, it shall be possible to override the libraries used by the RAs so us to upgrade the existing from Jboss. A similar XML approach can be used to define the libraries that have precedence.

**Comment by satanatoly** [comment]
You can use RA Library in order to override the classes.
For example please see:
https://github.com/RestComm/jain-slee.sip/tree/master/resources/sip11/library
