### ISSUE TITLE
can not run jss7 (jss7-management-console) 7.2.0 missing dependency jboss.security.security-domain.jmx-console

### ISSUE THREAD

**Issue by schaumannj** [RestComm/jain-slee#101]
Hi RestComm team,
I went through the installation manual http://documentation.telestax.com/core/ss7/SS7_Stack_Installation_Guide.html#introduction but I was not able to runn jss7 gui on jboss(wildfly) server.
I did:
download binaries of jss7  from https://github.com/RestComm/jss7/releases/tag/7.2.1390 and unzip
download server from dhis project https://github.com/RestComm/jain-slee/releases and unzip
set up the JBOSS_HOME to d:\devel\servers\restcomm-slee-7.0.63.64-wildfly-10.1.0.Final\wildfly-10.1.0.Final
run ant deploy in d:\devel\projects\restcomm-jss7-7.2.1390\ss7\
run jboss but the jss7 application was not in jboss
when I try to manually deploy the jss7-management-console.war from d:\devel\projects\restcomm-jss7-7.2.1390\oam\new-ui\ I've got this error

Cannot upload deployment: {"WFLYCTL0412: Required services that are not installed:" => ["jboss.security.security-domain.jmx-console"],"WFLYCTL0180: Services with missing/unavailable dependencies" => ["jboss.undertow.deployment.default-server.default-host./jss7-management-console.UndertowDeploymentInfoService is missing [jboss.security.security-domain.jmx-console]"]}

could you please help me

Jan

**Comment by SergeyLee** [comment]
Hi Jan!
If you want to work with jSS7 on WildFly (10.1.0.Final), you should to use branch jain-slee-3.x-2 and version 8.0.
You can find jSS7 in the RestComm JSLEE 7.0.0 release in folder extra/restcomm-jss7, but there old version 8.0.77.
You can use last build for JSLEE 7.0.0: 8.0.84 - https://mobicents.ci.cloudbees.com/job/Restcomm-jSS7/84/
jSS7 7.2 works only with JBoss 5.

Best regards,
Sergey Lee

**Comment by SergeyLee** [comment]
Close issue due an inactivity.
