### ISSUE TITLE
Jain slee build always insert the standalone.xml configuration.

### ISSUE THREAD

**Issue by duyanh030** [RestComm/jain-slee#104]
Whenever we do "ant build-core" in RestComm/jain-slee repository. It's **always** insert the jain-slee configuration in standalone.xml as below:
`<subsystem xmlns="urn:restcomm:slee-container:3.0">
.....
......
</subsystem>`

This is the reason that make standalone server start failed because duplicated configuration for jain-slee.
It's better to insert above lines if the jainslee configuration is not there.

**Comment by deruelle** [comment]
@duyanh030 wanna contribute a fix for that ?

**Comment by duyanh030** [comment]
@deruelle Ok. I will prepare a fix for it. :)

**Comment by deruelle** [comment]
@duyanh030 awesome
