### ISSUE TITLE
Snapshot dependency in pom

### ISSUE THREAD

**Issue by bkrok** [RestComm/jain-slee#108]
Hello,

you have SNAPSHOT dependency in container module pom:
<restcomm.cluster.version>3.0.0-SNAPSHOT</restcomm.cluster.version>
I assume that is not intended.

BR,
bkrok

**Comment by SergeyLee** [comment]
Hello @bkrok!
Yes, I will fix it. Now you can replace it with old 3.0.0.10 version or new 3.0.0.13 version.

Best regards,
Sergey

**Comment by SergeyLee** [comment]
Fixed.
