### ISSUE TITLE
Fix TracerFrameworkTest

### ISSUE THREAD

**Issue by EugeneyPutilin** [RestComm/jain-slee#115]
Hello All

Please fix TracerFrameworkTest.java I found public void test3GetTracersSet() doesn't cleanup Serve mode. As result if Test runs in random sort order it fails.
For example if test1Creation runs after test3GetTracersSet, it fails.
For fix next line should be added before catch.
			this.ts.unsetTracerLevel(orgMobicents.getTracerName());

The test4TestNotificationType also should be fixed with this code.

Thanks.

**Comment by deruelle** [comment]
Thanks @EugeneyPutilin. Do you want to contribute a fix for that ? Can you do a github pull request for this ?
