### ISSUE TITLE
Invalid commets on twiddle

### ISSUE THREAD

**Issue by duyanh030** [RestComm/jain-slee#117]
displayHelp() function ofhttps://github.com/RestComm/jain-slee/blob/master/tools/twiddle/cli/src/main/java/org/mobicents/tools/twiddle/jsleex/ActivityCommand.java#L61 show that the input value for setting TimeBetweenLivenessQueries value in "seconds".

But it should be in minutes instead.

**Comment by satanatoly** [comment]
Merged fix by @duyanh030 to master. Closing
