### ISSUE TITLE
Add "Is Ending" Activity state in twiddle output and slee-console-management.

### ISSUE THREAD

**Issue by duyanh030** [RestComm/jain-slee#120]
Command :
` ./twiddle.sh activity -l --contexts=true`
Currently ouput:

```
ACH               : 70d25df6:15d644a4188:-7fe4
Class             : org.mobicents.slee.container.service.ServiceActivityImpl
Last access time  : 1500626855107
Resource Adaptor  : null
SBB attached      : 
/ServiceID[name=SIP UAS,vendor=org.mobicents,version=1.0]/70d25df6:15d644a4188:-7fe4____
Names             : 
Timers Attached   : 
Data properties   : 
```

I would add 1 more information of activity state. It could help for debugging on activity leak issue.

> Is Ending         : false/ true.

I think it is good to add this information in slee-console-management too.

**Comment by duyanh030** [comment]
I will do PR on this issue asap

**Comment by satanatoly** [comment]
Added, closing

**Comment by duyanh030** [comment]
Hi @satanatoly could you show me the PR. I would like to test it.
