### ISSUE TITLE
NPE when clearing/raising alarm from an IES method

### ISSUE THREAD

**Issue by DanielBican** [RestComm/jain-slee#125]
After exchanging opinions on this thread https://groups.google.com/forum/#!topic/mobicents-public/uQhEDQ6-ydo I concluded that raising/clearing an alarm from an IES method will throw a NPE. 

I attached both the stacktrace and a demo slee service which, when installed, will trigger the NPE.

[demo.tar.gz](https://github.com/RestComm/jain-slee/files/1667117/demo.tar.gz)
[stacktrace.txt](https://github.com/RestComm/jain-slee/files/1667129/stacktrace.txt)

**Comment by gsaslis** [comment]
Thanks a lot for raising this here @DanielBican !  I did follow the discussion on the high level.

Do you think you would also be in a position to have a go at contributing a fix for this?

**Comment by DanielBican** [comment]
Thank you also for reaching to me on this topic.

I think I can try to fix it. Could you give me some directions regarding the contribution process (e.g. docs, examples, anything that could help me on the way of contributing)?

**Comment by gsaslis** [comment]
Sorry for the delayed reply here @DanielBican ... :(

Could you please take a look at our [Open Source Playbook](https://docs.google.com/document/d/1RZz2nd2ivCK_rg1vKX9ansgNF6NpK_PZl81GxZ2MSnM/edit) and then make sure to @mention me directly, if you have any additional questions or need any further help at all?  ; )

Thanks in advance!! 👍 
Yorgos

**Comment by satanatoly** [comment]
thank you @DanielBican for bringing up the issue and providing test binaries. Applied [fix](https://github.com/RestComm/jain-slee/commit/2249abef9cac10dfbe0600d384f7138b1cd9de51) 
will be included in next release, closing
