### ISSUE TITLE
Build fails for JDK9 or later

### ISSUE THREAD

**Issue by philipp-birkl** [RestComm/jain-slee#138]
While trying to build `jain-slee` version `7.2.0-186` I encountered a problem with the default `maven-compiler-plugin`, as it is using java 1.5 as source and target option out of the box. However those versions are not supported by the latest JDK's anymore. Please find my maven output in the attachment.

[jain-compile-error.txt](https://github.com/RestComm/jain-slee/files/3202055/jain-compile-error.txt)

**Comment by nhanth87** [comment]
you only can build jainslee with jv 7 and jv8 (wildfly version).
If you weant to build it with jv9, you need to modify pom file
