### ISSUE TITLE
Support separator ";" in twiddle command to fill profile array type

### ISSUE THREAD

**Issue by nhanth87** [RestComm/jain-slee#19]
From ticket 33014:
At this time, an array type is only filled by manual set from JMX.
We need to add this feature in twiddle because some customers use twiddle to automate the create profile process.
Example:
`profile.edit CallControl mobile.user -s --name=userPhone separator=; --value=”something;other stuff;something else”`

**Comment by SergeyLee** [comment]
@nhanth87 Did you remember how you manual set array type from JMX?
For example, I try to set String[] type to "100;200;300" and it saves attribute only with one value String "100;200;300".

**Comment by nhanth87** [comment]
Hi,
The ticket is not about create an "array", it's all about ; character

Br,
TN

**Comment by SergeyLee** [comment]
Hi @nhanth87 
I am working with this issue now and if you have any question or comment please write them.

**Comment by SergeyLee** [comment]
So I developed logic for using separator (";" or another) and populate arrays: if we set "aa;b;ccc" then we get String array with "aa", "b" and "ccc" values. I should only fix this logic for primitive array (int, long, float, etc) see issue #47.
@nhanth87  So as I understand we don't need this parsing logic, am I right?
