### ISSUE TITLE
We need some kind of automate create profile when jain-slee start

### ISSUE THREAD

**Issue by nhanth87** [RestComm/jain-slee#20]
From the ticket 33014:
We need some mechanism to create, store profile at starting time of jain-slee (load it from xml file)

**Comment by SergeyLee** [comment]
Hi @nhanth87 
Is this mechanism necessary now? If yes then I will investigate this issue for new JSLEE 7 (7.1.0 milestone).

**Comment by SergeyLee** [comment]
As I know JSLEE can store profile tables and profiles into database. If we set default database (HSQLDB for JBoss 5.1 and H2 for WildFly) as in-memory then JSLEE don't store any profile data and we need set this default database for write operations.
Also JSLEE has beans based on org.mobicents.slee.container.deployment.profile.jpa.Configuration and we can set persistProfiles property for store profile data (set to "true") or don't store profile data (set to "false").
