### ISSUE TITLE
SLEE Console should configure RA Entity properties with various type

### ISSUE THREAD

**Issue by gfigiel** [RestComm/jain-slee#33]
Same problem as for issue #17 but related to Long properties. More generic fix/enhancement to SMC tool is required in order to support other java Types as well.

Caused by: java.lang.IllegalArgumentException: Value is of type java.lang.String, required type is java.lang.Long
        at javax.slee.resource.ConfigProperties$Property.setValue(ConfigProperties.java:171)
        at javax.slee.resource.ConfigProperties$Property.<init>(ConfigProperties.java:133)
        at org.mobicents.slee.container.management.console.server.PropertiesInfoUtils.toProperties(PropertiesInfoUtils.java:70)
        at

**Comment by gfigiel** [comment]
As to fix the issue reimplementation of this code fragment is needed.

https://github.com/RestComm/jain-slee/blob/2.x/tools/slee-management-console/server/src/main/java/org/mobicents/slee/container/management/console/server/PropertiesInfoUtils.java#L58-L68

I could do it, however I need clarification on repo organization as I cannot see tools folder in master branch hoever it is in 2.x branch...

**Comment by gfigiel** [comment]
Fixed as per Pull Request #34:  Fixes #33 - Support for other Resource Adaptor config parameter types #34

**Comment by SergeyLee** [comment]
Thank you Grzegorz! I merge it ASAP after local testing.

**Comment by SergeyLee** [comment]
@gfigiel 
Ok. I tested it and it works well to support other java Types.
Please remove  ```+ e.getMessage()```  because it always return ```null```. Exception has type **java.lang.reflect.InvocationTargetException**.
Then I will merge your PR.

**Comment by SergeyLee** [comment]
Ok. I fix it self.

**Comment by gfigiel** [comment]
Thanks. Just please add exception stack in order to have something in case of ClassNotFoundException that may occure in forName() call.
