### ISSUE TITLE
[Twiddle] Profile attribute setting problem.

### ISSUE THREAD

**Issue by SergeyLee** [RestComm/jain-slee#40]
This problem causes when attribute value has braces and is not quotation.

For example:
this command is setting wrong value

> ./twiddle.sh profile.edit MyTable MyProfile --set --name=Info --value=0{2,3}[1-9][0-9][0-9]{9,10}

but this command works well

> ./twiddle.sh profile.edit MyTable MyProfile --set --name=Info --value="0{2,3}[1-9][0-9][0-9]{9,10}"

**Comment by SergeyLee** [comment]
Notes:
Problem is here: https://github.com/RestComm/jain-slee/blob/2.x/tools/twiddle/cli/src/main/java/org/mobicents/tools/twiddle/jslee/ProfileEditCommand.java#L513-L533

**Comment by jaimecasero** [comment]
this is bash tweaking argument before passing into command
[root@restcomm ~]# echo 0{2}[1-9][0-9][0-9]{9,10}
0{2}[1-9][0-9][0-9]9 0{2}[1-9][0-9][0-9]10
[root@restcomm ~]#

**Comment by SergeyLee** [comment]
Ok. With curly braces we have Bash Brace expansion. So we can only update twiddle doc for this case.
