### ISSUE TITLE
[Usage] Display proper value of sample attribute, rather than MIN/MAX

### ISSUE THREAD

**Issue by baranowb** [RestComm/jain-slee#55]
diff --git a/container/usage/src/main/java/org/mobicents/slee/runtime/usage/UsageParameter.java b/container/usage/src/main/java/org/mobicents/slee/runtime/usage/UsageParameter.java
index a5c2d99..ce946d0 100644
--- a/container/usage/src/main/java/org/mobicents/slee/runtime/usage/UsageParameter.java
+++ b/container/usage/src/main/java/org/mobicents/slee/runtime/usage/UsageParameter.java
@@ -47,6 +47,7 @@ public class UsageParameter implements Serializable {
        // NOTE: it seems that javassit does some sort of magic here - cause with
        // generated code and "long" tck passes ... 
        // private long value;
- ```
    private static final int NOT_INITIALIZED_VALUE=0;
  private BigDecimal value;
  private long min;
  private long max;
  ```
  
  @@ -78,6 +79,9 @@ public class UsageParameter implements Serializable {
      }
  
  ```
  public long getMin() {
  ```
-               if(this.count == 0){
-                       return NOT_INITIALIZED_VALUE;
-               }
              return min;
      }

@@ -86,6 +90,9 @@ public class UsageParameter implements Serializable {
        }

```
    public long getMax() {
```
-               if(this.count == 0){
-                       return NOT_INITIALIZED_VALUE;
-               }
              return max;
      }

**Comment by SergeyLee** [comment]
This fix cause TCK assertion:

> Failed assertion ID: 4642 Failure context/reason: Exception: com.opencloud.sleetck.lib.TCKTestFailureException => SampleStatistics.getMinimum() returned an invalid value. Expected=9223372036854775807; minimum value returned=0; Sample set:{<Empty set>} Stack Trace: com.opencloud.sleetck.lib.TCKTestFailureException: SampleStatistics.getMinimum() returned an invalid value. Expected=9223372036854775807; minimum value returned=0; Sample set:{<Empty set>} at com.opencloud.sleetck.lib.testsuite.javax.slee.usage.SampleStatistics.SampleStatisticsTest.auditStatistics(SampleStatisticsTest.java:114) at com.opencloud.sleetck.lib.testsuite.javax.slee.usage.SampleStatistics.SampleStatisticsTest.testSampleSet(SampleStatisticsTest.java:49) at com.opencloud.sleetck.lib.testsuite.javax.slee.usage.SampleStatistics.SampleStatisticsTest.run(SampleStatisticsTest.java:40) at com.opencloud.sleetck.lib.infra.SleeTCKScript.run(Unknown Source) at com.sun.javatest.Script.run(Script.java:213) at com.sun.javatest.Harness.runTest(Harness.java:695) at com.sun.javatest.Harness.access$900(Harness.java:27) at com.sun.javatest.Harness$2.run(Harness.java:854)
