### ISSUE TITLE
How to install jain-slee with JBoss AS

### ISSUE THREAD

**Issue by jeenareload** [RestComm/jain-slee#74]
HI,
I have downloaded JBoss AS 5/7 from jboss website, Now i want install jain-slee into JBoss AS. 

NEED HELP

**Comment by SergeyLee** [comment]
Hi!
You can download [RestComm JSLEE 2.8.0.FINAL](https://github.com/RestComm/jain-slee/releases/tag/2.8.0.FINAL).
Also you can download the Binary zip files from https://mobicents.ci.cloudbees.com/job/Restcomm-JAIN-SLEE-Release/lastSuccessfulBuild/artifact/release/.
Read more here: [RestComm JSLEE documentation](http://documentation.telestax.com/core/jain_slee/JAIN_SLEE_User_Guide.html#_install)

**Comment by georgeyanev** [comment]
@SergeyLee the link to the binary zip files does not work. Please provide a valid one.

**Comment by Eloyjaws** [comment]
Hey, has anyone been able to find a valid link to the binary zip file?
