### ISSUE TITLE
Graceful shutdown feature implementation

### ISSUE THREAD

**Issue by gfigiel** [RestComm/jain-slee#75]
Gracefull shutdown feature allows shutdown SLEE without forcefull activities ending for supporting RAs.

When slee goes into graceful stopping mode it notifies supporting RAs as not to create new activities but allows current activities to be processed until standard stop procedure is called (with activities ending schedule).

The feature is triggered using JMX call.

Detail feature requirements as in TX case: https://telestax.zendesk.com/hc/en-us/requests/33478

**Comment by gfigiel** [comment]
Feature implementation added in commit: https://github.com/gfigiel/jain-slee/commit/0b89725f29a53d3ae315e2a97021bc24eba08d80 on 2.x based branch

**Comment by gfigiel** [comment]
Pull request created: https://github.com/RestComm/jain-slee/pull/76

**Comment by SergeyLee** [comment]
I don't see GracefullyStopableResourceAdaptor class in commit.
And please create pull request with last changes.

**Comment by gfigiel** [comment]
Hello,
We are now ready to contribute this feature so please assign me to this case.

**Comment by deruelle** [comment]
@gfigiel great ! done

**Comment by gfigiel** [comment]
Pull request done. The provided changes enables any RA to be prepared for graceful shutdown.

**Comment by SergeyLee** [comment]
Hi @gfigiel 
From yesterday I am working on this feature for JSLEE 7 branch **master** (milestone 7.1.0), but then we can fix it for branch 2.x and then for TelScale 6.1.x.
I will review your code today.

**Comment by satanatoly** [comment]
closing, implemented alternative of graceful shutdown in TelScale version
