### ISSUE TITLE
Create file naming convention to ensure proper DU deployment order

### ISSUE THREAD

**Issue by jaimecasero** [RestComm/jain-slee#78]
Sometimes a solutino is based on multiple DUs which complex dependency network. There is a natural ordering  in SLEE being baseLibs->RAs->libs->sbb . Although integrator have the pssibility to influence the deployment order using JBoss features (deplay.last alphabeticalOrder), it would be great to enforce a certain order by suggesting a file name convention. This would require to configure the Jboss built-in comparator and adding new suffixes to support specific slee extensions, instead of current all  "jar" files
.sra->.slib->.sbb (try to use S as in SLEE to differenciate other EE artifacts

**Comment by SergeyLee** [comment]
My idea is adding priority to DUs. For all DUs we have default priority (eg. 10). We can set low or high priority in deploy-config for DUs which we want load early or later.

**Comment by jaimecasero** [comment]
can you be more specific on how a DU would populate that descriptor?

**Comment by SergeyLee** [comment]
BTW we had problem with customer's service deployment order because our jSS7 stack is initialized from SS7 RAs. If we can initialize jSS7 stack as we initialize jDiameter Mux then perhaps SS7 RAs will deploy more quicky.

**Comment by SergeyLee** [comment]
Hi @jaimecasero 
The question is: this issue is needed only for JSLEE 2.x/JBoss 5.1 or we may think about deployment order and DU priority also for new JSLEE 7.x/WildFly?
What do you think about this?
For WildFly we can read about this topic here (with links to documentation):
http://serverfault.com/questions/693161/what-is-the-order-of-deployment-in-wildfly

**Comment by jaimecasero** [comment]
@SergeyLee I think deployment order still is applicable to any server, including new Wildfly10. Customers will have solutions based on many DUs, where sometimes lifecycle requires certain order to be honored during server startup. Although this behavior is not defined in Spec, we should try to provide a vendor extension to allow this. This is probably not the most urgent issue, but its an additional feature we should plan in the roadmap...
