### ISSUE TITLE
Integrate the Restcomm Statistics

### ISSUE THREAD

**Issue by deruelle** [RestComm/jain-slee#84]
For every SMS or Calls (and related # of minutes for the call) sent or received either through SMPP,  SS7, SIP we should ping the Restcomm statistics server at the end of the day. The integration on the JAIN SLEE side happens through this project https://github.com/RestComm/commons/tree/master/statistics.

Ping me for more guidance

**Comment by SergeyLee** [comment]
@deruelle Should 3.0.0 Release include this feature?

**Comment by deruelle** [comment]
@SergeyLee Yes. You can sync up with @vetss on how to enable it, he went through the exercise a couple of times for SMSC and USSD GW.

**Comment by SergeyLee** [comment]
Hi @deruelle!
I investigated same issue for USSD: https://github.com/RestComm/ussdgateway/issues/39
I have a question: what metrics we should/can provided for JSLEE?
From JSLEE spec and modules: sbbs, events, transactions, facilities and active objects.

**Comment by deruelle** [comment]
@SergeyLee we should provide that in the Resource Adaptors I think. We don't want to record all type of events. Only number of SMS, USSD Messages processed and sent and number of Voice Calls and number of minutes processed and sent in a day
