### ISSUE TITLE
jainslee tool twiddle.sh can't create profile

### ISSUE THREAD

**Issue by nhanth87** [RestComm/jain-slee#9]
Confirm twiddle can't create profile.

Reproduce:
./twiddle.sh -slocalhost:1099 profile -c  --table-name=tele-table --profile-spec=ProfileSpecificationID[name=AddressProfileSpec,vendor=javax.slee,version=1.1]

./twiddle.sh -slocalhost:1099 profile -c  --table-name=tele-table --profile-name=profile_demo

./twiddle.sh -slocalhost:1099 profile.edit tele-table demo10 -d

and get table or profile not exits.
after some time, profile removed from jainslee due to timeout:
 14:46:42,180 WARN  [arjLoggerI18N] (Thread-9) [com.arjuna.ats.arjuna.coordinator.TransactionReaper_18] - TransactionReaper::check timeout for TX 7f000101:bf7b:56bae987:be in state  RUN
14:46:42,181 WARN  [arjLoggerI18N] (Thread-10) [com.arjuna.ats.arjuna.coordinator.TransactionReaper_7] - TransactionReaper::doCancellations worker Thread[Thread-10,5,jboss] successfully canceled TX 7f000101:bf7b:56bae987:be

BR,
TN

**Comment by nhanth87** [comment]
When profile create, a temp profile created at javax.slee.profile

The profile.edit commit try to invoke javax.slee.management.ProfileProvisioningMBean so it can't find entry for temp profile. Also in the code of twiddle, there's no invoke of javax.slee.profile.

**Comment by SergeyLee** [comment]
I fixed ProfileEditCommand with checking if main operation is commitProfile and execute after createProfile.
Bug reason: ProfileProvisioning MBean can not execute getProfile for new profile after createProfile execution.
