### ISSUE TITLE
[Tools] Slee-management-console

### ISSUE THREAD

**Issue by bkrok** [RestComm/jain-slee#97]
Hello, is it possible to present value of env-entry in gui slee-management-console Sbb specific information panel? Could you give some advices how to reach this feature?

**Comment by duyanh030** [comment]
Hi @SergeyLee . I am working on this issue if it's ok to implement it.

**Comment by SergeyLee** [comment]
Hi @duyanh030 . Sure, you can investigate and fix it.

**Comment by satanatoly** [comment]
Merged PR https://github.com/RestComm/jain-slee/pull/102 to master. Closing
