### ISSUE TITLE
[configuration] Add security-domain (jmx-console) with properties.

### ISSUE THREAD

**Issue by SergeyLee** [RestComm/jain-slee#99]

**Comment by vetss** [comment]
We have several GUI / CLI interfaces for JSS7, SMPP projects (and also for USSD, SMSC, CAMEL, GMLC GWs), we have slee-management-console, we have KMX access (that we make via "jconsole" tool).

May be we can create a SLEE-level security-domain(s) with initial preconfigured credentials to which our products will reuse.
